### ISSUE TITLE
Import Order Dependency Issue Between nnsight and umap

### ISSUE THREAD

**Issue by Nuisal** [ndif-team/nnsight#310]
## Description
There appears to be a compatibility issue between nnsight and umap libraries that manifests depending on the import order. When umap is imported before nnsight, the code fails with a Numba typing error. However, the same code works when nnsight is imported before umap.

## Environment
- OS: Ubuntu 22.04.1
- Python: 3.12.7
- nnsight: 0.3.7
- umap-learn: 0.5.7 (https://umap-learn.readthedocs.io/en/latest/)

Note: The issue has been reproduced on Python 3.10 on other machine as well.

### Failing Case
```python
import numpy as np
from umap import UMAP
import nnsight

X = np.random.rand(100, 10)

reducer = UMAP(n_components=3)
X_reduce = reducer.fit_transform(X)
```

### Working Case
```python
import numpy as np
import nnsight
from umap import UMAP

X = np.random.rand(100, 10)

reducer = UMAP(n_components=3)
X_reduce = reducer.fit_transform(X)
```

## Error Message
```
TypingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'pow' of type Module(<module 'math' from '/home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>)

[... stack trace details ...]

During: lowering "$binop_pow86.11 = $binop_sub80.9 ** $const84.10" at /home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/site-packages/umap/distances.py (31)
```
## Full Error Message
```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
File /data/zhoupeilin/code/chromalens/sam_sight/test_tsne/test_umap.py:8
      5 X = np.random.rand(100, 10)
      7 reducer = UMAP(n_components=3)
----> 8 X_reduce = reducer.fit_transform(X)

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/umap/umap_.py:2928, in UMAP.fit_transform(self, X, y, force_all_finite, **kwargs)
   2890 def fit_transform(self, X, y=None, force_all_finite=True, **kwargs):
   2891     """Fit X into an embedded space and return that transformed
   2892     output.
   2893 
   (...)
   2926         Local radii of data points in the embedding (log-transformed).
   2927     """
-> 2928     self.fit(X, y, force_all_finite, **kwargs)
   2929     if self.transform_mode == "embedding":
   2930         if self.output_dens:

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/umap/umap_.py:2555, in UMAP.fit(self, X, y, force_all_finite, **kwargs)
   2552 try:
   2553     # sklearn pairwise_distances fails for callable metric on sparse data
   2554     _m = self.metric if self._sparse_data else self._input_distance_func
-> 2555     dmat = pairwise_distances(X[index], metric=_m, **self._metric_kwds)
   2556 except (ValueError, TypeError) as e:
   2557     # metric is numba.jit'd or not supported by sklearn,
   2558     # fallback to pairwise special
   2560     if self._sparse_data:
   2561         # Get a fresh metric since we are casting to dense

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:213, in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    207 try:
    208     with config_context(
    209         skip_parameter_validation=(
    210             prefer_skip_nested_validation or global_skip_validation
    211         )
    212     ):
--> 213         return func(*args, **kwargs)
    214 except InvalidParameterError as e:
    215     # When the function is just a wrapper around an estimator, we allow
    216     # the function to delegate validation to the estimator, but we replace
    217     # the name of the estimator by the name of the function in the error
    218     # message to avoid confusion.
    219     msg = re.sub(
    220         r"parameter of \w+ must be",
    221         f"parameter of {func.__qualname__} must be",
    222         str(e),
    223     )

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/sklearn/metrics/pairwise.py:2375, in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   2372         return distance.squareform(distance.pdist(X, metric=metric, **kwds))
   2373     func = partial(distance.cdist, metric=metric, **kwds)
-> 2375 return _parallel_pairwise(X, Y, func, n_jobs, **kwds)

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/sklearn/metrics/pairwise.py:1893, in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1890 X, Y, dtype = _return_float_dtype(X, Y)
   1892 if effective_n_jobs(n_jobs) == 1:
-> 1893     return func(X, Y, **kwds)
   1895 # enforce a threading backend to prevent data communication overhead
   1896 fd = delayed(_dist_wrapper)

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/sklearn/metrics/pairwise.py:1930, in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1928     x = X[[i], :] if issparse(X) else X[i]
   1929     y = Y[[j], :] if issparse(Y) else Y[j]
-> 1930     out[i, j] = metric(x, y, **kwds)
   1932 # Make symmetric
   1933 # NB: out += out.T will produce incorrect results
   1934 out = out + out.T

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/numba/core/dispatcher.py:423, in _DispatcherBase._compile_for_args(self, *args, **kws)
    419         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    420                f"by the following argument(s):\n{args_str}\n")
    421         e.patch_message(msg)
--> 423     error_rewrite(e, 'typing')
    424 except errors.UnsupportedError as e:
    425     # Something unsupported is present in the user code, add help info
    426     error_rewrite(e, 'unsupported_error')

File ~/anaconda3/envs/nnsight/lib/python3.12/site-packages/numba/core/dispatcher.py:364, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    362     raise e
    363 else:
--> 364     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'pow' of type Module(<module 'math' from '/home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>)

File "../../../../../../home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/site-packages/numba/cpython/numbers.py", line 236:
    def int_power(a, b):
        <source elided>
            # Optimization cutoff: fallback on the generic algorithm
            return math.pow(a, float(b))
            ^

During: typing of get attribute at /home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/site-packages/numba/cpython/numbers.py (236)

File "../../../../../../home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/site-packages/numba/cpython/numbers.py", line 236:
    def int_power(a, b):
        <source elided>
            # Optimization cutoff: fallback on the generic algorithm
            return math.pow(a, float(b))
            ^

During: lowering "$binop_pow86.11 = $binop_sub80.9 ** $const84.10" at /home/zhoupeilin/anaconda3/envs/nnsight/lib/python3.12/site-packages/umap/distances.py (31)
```

**Comment by JadenFiotto-Kaufman** [comment]
@Nuisal Hey! This is fixed in the 0.4 version of nnsight which you can install via `pip install nnsight==0.4.0.dev0`. This will be the latest stable version sometime soon after thew new year.
